# Generated by Django 4.1.7 on 2023-03-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_contact_remove_confirmedbooking_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
